[tool.black]
line-length = 127
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 127
skip = ["migrations", ".venv", "venv"]
skip_glob = ["**/migrations/*.py"]